# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f633bef1daadf5175a1cecbc499f275bd2d1ae615e1bcfa9f07441b7bef30303c6346be833f6e02e3eb244a7e66bf54d4ea86b146b48f7bac09f5b537deedf

test:
  secret_key_base: 46a78684d8693a63163bad2cf5181f7afbfd1ac838dcf811969497cc7a9dbd86b8916744a01366488dbabe986fa583dba36767d6c740a1f6d4d0d2ab8136f451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
